#ifndef SIMPLE_LANG_SETTINGS_H
#define SIMPLE_LANG_SETTINGS_H

#define MAX_TOKEN 200
#define MAX_STATEMENT 100

#define MAX_INSTR_IN_STATEMENT 100
#define STAKE_LENGTH 200

#define MAX_SOURCE_LENGTH 2000

#define DEBUG 0

#endif //SIMPLE_LANG_SETTINGS_H
